GitHub signup and PAT instructions
ImperialCollegeLondon/grad_school_git_course pull request #24
Opened 2021-11-30 13:46 UTC by dandavies99

This PR adds instructions to create a GitHub account and for accessing GitHub from the command line using personal access tokens. Some questions I have: 

- Are the GitHub joining instructions in the right place and do they make sense? 
- Should we add any instructions on using SSH instead of HTTPS?
- Are there any Windows-specific differences we need to consider (I haven't been able to test this)?

Closes #19, closes #22.

2021-12-02 12:11 UTC, AdrianDAlessandro commented
All the text is great. Perhaps the GitHub joining and PAT instructions should be in the pre-class setup instructions. But I think it's quick enough for students to do in the class, and with GitHub being the second day, it might be better to make them wait until then to not confuse things.

I personally find SSH keys a bit more confusing. HTTPS just means users have to paste the key when they need the password. Might be simpler to just mention SSH by including something like "If you're familiar with SSH keys, you can follow [these instructions](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to use that alternative authentication method"

I am unsure about Windows too.

2021-12-02 14:07 UTC, dandavies99 commented
Yeah I think it makes logical sense to put it in the pre-class setup, but I think it's a bit too much setup in one go alongside git itself. Thanks, that sentence on SSH keys with the link fits nicely.

2021-12-03 09:49 UTC, AdrianDAlessandro approved these changes
I'm happy to approve this. But maybe you want to wait for Chris also?

2021-12-06 11:42 UTC, cc-a requested changes
We need something like the following instructions for Windows users the first time they push to github.

> You will be presented with a CredentialHelperSelector dialog box. Ensure "manager-core" is selected and check the box for "Always use this from now on". Press Select. From the next  dialog select "Token" then paste the PAT you saved earlier and press "Sign in". On subsequent interactions with GitHub your credentials will be remembered and you will not be prompted.

2021-12-09 08:56 UTC, dandavies99 commented
Thanks @cc-a - I've added that in.

2021-12-09 09:55 UTC, cc-a requested changes
In my experience people aren't great at reading ahead to see the instructions specific for their system. Could we do something like:

> **Mac and Linux users** you will be asked to provide your GitHub username and password
> Enter your personal access token (PAT) as your password. 
> **Windows users:** You will be presented with a CredentialHelperSelector dialog box. 
> Ensure "manager-core" is selected and check the box for "Always use this from now 
> on". Press Select. From the next dialog select "Token" then paste the PAT you saved 
> earlier and press "Sign in". On subsequent interactions with GitHub your credentials 
> will be remembered and you will not be prompted.

2021-12-09 10:47 UTC, dandavies99 commented
Good idea, I've re-jigged.

2021-12-09 10:47 UTC, cc-a approved these changes
Looks good to me.

2021-12-09 10:48 UTC, merged