L2 02 remote repositories
ImperialCollegeLondon/grad_school_git_course pull request #3
Opened 2020-01-13 09:24 UTC by dalonsoa

2020-01-13 12:04 UTC, cc-a approved these changes
Thanks Diego. Looks very good. If we have time it would be nice to include a diagram or two illustrating the relationship between different the various components.

2020-01-22 10:49 UTC, cc-a requested changes
Thanks Diego. Diagrams are great, I may revise for consistency with the last lesson if there is time.
Couple of other very minor points.

2020-01-22 16:25 UTC, dalonsoa reviewed
I think I've implemented all changes, now.

2020-01-24 15:11 UTC, cc-a approved these changes

2020-01-24 15:12 UTC, merged